config/routes.rb
Rails.application.routes.draw do
  get 'location/index'
  get 'expense_report', to: "expense_report#index"
  post 'expense_report', to: "expense_report#index"
  resources :order_items
  resources :items
  resources :order_vendors
  resources :vendors
  resources :states
  resources :orders
  resources :statuses
  get 'menu/index'
  get 'menu/dessert'
  get 'menu/beverages'
  get 'menu/sideitems'
  get 'menu/vermicelli'
  get 'menu/friedriceplate'
  get 'menu/steamedriceplate'
  get 'menu/eggnoodlesoup'
  get 'menu/chickennoodlesoup'
  get 'menu/special'
  get 'menu/beefnoodlesoups'
  get 'menu/appetizers'
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense_report.rb
class ExpenseReport

  def self.buy_by_product_in_range(starting,ending)
    Order.where("date_of_purchase >= '#{starting}' and date_of_purchase <= '#{ending}'")# .group(:product).count
  end

  def self.buy_in_range_arel(starting,ending)
    orders = Order.arel_table
    Order.where(orders[:date_of_purchase].between(starting..ending))# .group(:product).count
  end

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_items
  has_many :orders, through: :order_items

  validates_presence_of :name
  validates :price, numericality: {greater_than: 0}

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :status
  has_many :order_vendors, dependent: :destroy
  has_many :vendors, through: :order_vendors

  has_many :order_items, dependent: :destroy
  has_many :items, through: :order_items

  validates_presence_of :name

  after_save :calculate_total

  accepts_nested_attributes_for :order_vendors, :allow_destroy => true
  accepts_nested_attributes_for :order_items, :allow_destroy => true

  def calculate_total
    # sub_total = menu_items.map(&:price).sum * menu_orders.collect {|| .}
    sub_total = order_items.collect { |li| li.valid? ? (li.quantity * li.item.price ) : 0 }.sum
    tax = sub_total * 0.10
    update_columns(sub_total: sub_total, tax: tax)
  end

  def total_amount
    sub_total + tax
  end


  def self.sum_price
    Order.sum(:total_amount)
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

  validates :quantity, numericality: {greater_than: 0}

end

app/models/order_vendor.rb
class OrderVendor < ApplicationRecord
  belongs_to :vendor
  belongs_to :order
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  belongs_to :state
  has_many :order_vendors
  has_many :orders, through: :order_vendors

  validates_presence_of :name
  validates_presence_of :street
  validates_presence_of :zipcode
  validates_presence_of :city
  validates :fname, presence: true
  validates :lname, presence: true
  validates :phone, format: { with: /\d{3}-\d{3}-\d{4}/, message: "bad format" }



end

app/controllers/expense_report_controller.rb
class ExpenseReportController < ApplicationController
  def index
    if request.get?
      @orders = Order.all
    else
      start_date = params[:start_date]
      end_date = params[:end_date]

      unless (start_date.nil? || end_date.nil?)
        @orders = ExpenseReport.buy_in_range_arel(start_date, end_date)
        if start_date > end_date
          respond_to do |format|
            format.html {redirect_to expense_report_url, notice: 'Invalid Input.'}
            format.json {head :no_content}
          end

        end


      end


    end
    # @item_average_price = Order.sum_price
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def appetizers
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expense_report_helper.rb
module ExpenseReportHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/expense_report/index.html.erb
<h1>Expense Report</h1>
<p id="notice"><%= notice %></p>
<%= form_tag(expense_report_path, :method => :post) do %>

  <h3>Start Date</h3>
  <%= date_field_tag :start_date %>

  <h3>End Date</h3>
  <%= date_field_tag :end_date %>

  <br>

  <%= submit_tag "Submit " %>

<% end %>
<h1>Orders</h1>

<%#= submit_tag "Export to Excel", onclick: "tableToExcel ('testTable')", remote: true %>
<button onclick="tableToExcel('testTable', 'W3C Example Table')" > Export to Excel</button>
<table class="greenTable" id="testTable">
  <thead class="">
  <tr>
    <th>Invoice Number</th>
    <th>Date of Purchase</th>
    <th>Sub Total</th>
    <th>Tax</th>
    <th>Total Amount</th>
    <th>Status</th>
    <th>Vendor Name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody class="table table-hover">
  <% @orders.each do |order| %>
    <tr>
      <td><%= order.name %></td>
      <td><%= order.date_of_purchase %></td>
      <td><%= number_to_currency(order.sub_total) %></td>
      <td><%= number_to_currency(order.tax) %></td>
      <td><%= number_to_currency(order.total_amount) rescue "NA" %></td>
      <td><%= order.status.name %></td>
      <td>
        <% order.order_vendors.each do |vendor| %>  <%= vendor.vendor.name %>
        <% end %>  </td>

      <td><%= button_to 'Show', order, method: :get %></td>
      <!--      <td><%#= link_to 'Edit', edit_order_path(order) %></td>-->
      <!--      <td><%#= link_to 'Destroy', order, method: :delete, data: {confirm: 'Are you sure?'} %></td>-->


    </tr>
  <% end %>
  </tbody>
</table>
<!--<p>The <span id="" class="bold-blue">total</span> price of a sales item is <%#= number_to_currency(@item_average_price) %>.</p>-->
<br>

<%#= link_to 'New Order', new_order_path %>