config/routes.rb
Rails.application.routes.draw do
  get 'location/index'
  get 'expense_report', to: "expense_report#index"
  post 'expense_report', to: "expense_report#index"
  resources :order_items
  resources :items
  resources :order_vendors
  resources :vendors
  resources :states
  resources :orders
  resources :statuses
  get 'menu/index'
  get 'menu/dessert'
  get 'menu/beverages'
  get 'menu/sideitems'
  get 'menu/vermicelli'
  get 'menu/friedriceplate'
  get 'menu/steamedriceplate'
  get 'menu/eggnoodlesoup'
  get 'menu/chickennoodlesoup'
  get 'menu/special'
  get 'menu/beefnoodlesoups'
  get 'menu/appetizers'
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense_report.rb
class ExpenseReport

  def self.buy_by_product_in_range(starting,ending)
    Order.where("date_of_purchase >= '#{starting}' and date_of_purchase <= '#{ending}'")# .group(:product).count
  end

  def self.buy_in_range_arel(starting,ending)
    orders = Order.arel_table
    Order.where(orders[:date_of_purchase].between(starting..ending))# .group(:product).count
  end

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_items
  has_many :orders, through: :order_items

  validates_presence_of :name
  validates :price, numericality: {greater_than: 0}

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :status
  has_many :order_vendors, dependent: :destroy
  has_many :vendors, through: :order_vendors

  has_many :order_items, dependent: :destroy
  has_many :items, through: :order_items

  validates_presence_of :name

  after_save :calculate_total

  accepts_nested_attributes_for :order_vendors, :allow_destroy => true
  accepts_nested_attributes_for :order_items, :allow_destroy => true

  def calculate_total
    # sub_total = menu_items.map(&:price).sum * menu_orders.collect {|| .}
    sub_total = order_items.collect { |li| li.valid? ? (li.quantity * li.item.price ) : 0 }.sum
    tax = sub_total * 0.10
    update_columns(sub_total: sub_total, tax: tax)
  end

  def total_amount
    sub_total + tax
  end


  def self.sum_price
    Order.sum(:total_amount)
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

  validates :quantity, numericality: {greater_than: 0}

end

app/models/order_vendor.rb
class OrderVendor < ApplicationRecord
  belongs_to :vendor
  belongs_to :order
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  belongs_to :state
  has_many :order_vendors
  has_many :orders, through: :order_vendors

  validates_presence_of :name
  validates_presence_of :street
  validates_presence_of :zipcode
  validates_presence_of :city
  validates :fname, presence: true
  validates :lname, presence: true
  validates :phone, format: { with: /\d{3}-\d{3}-\d{4}/, message: "bad format" }



end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :price, :description)
    end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def appetizers
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: [:show, :edit, :update, :destroy]

  # GET /vendors
  # GET /vendors.json
  def index
    @vendors = Vendor.all
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: 'Vendor was successfully created.' }
        format.json { render :show, status: :created, location: @vendor }
      else
        format.html { render :new }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1
  # PATCH/PUT /vendors/1.json
  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to @vendor, notice: 'Vendor was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor.destroy
    respond_to do |format|
      format.html { redirect_to vendors_url, notice: 'Vendor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendor_params
      params.require(:vendor).permit(:name, :phone, :fname, :lname, :street, :city, :state_id, :zipcode)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_form.html.erb
<%= form_with(model: vendor, local: true) do |form| %>
  <% if vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
      <% vendor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "Vendor Name" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :fname , "First Name"%>
    <%= form.text_field :fname %>
  </div>

  <div class="field">
    <%= form.label :lname, "Last Name" %>
    <%= form.text_field :lname %>
  </div>

  <div class="field">
    <%= form.label :street %>
    <%= form.text_field :street %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state_id %>
    <%= form.collection_select :state_id, State.all,:id, :name %>
  </div>

  <div class="field">
    <%= form.label :zipcode, "Zip Code" %>
    <%= form.text_field :zipcode %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vendors/edit.html.erb
<h1>Editing Vendor</h1>

<%= render 'form', vendor: @vendor %>

<%= link_to 'Show', @vendor %> |
<%= link_to 'Back', vendors_path %>

app/views/vendors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vendors</h1>

<table class="greenTable">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Fname</th>
      <th>Lname</th>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th>Zipcode</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vendors.each do |vendor| %>
      <tr>
        <td><%= vendor.name %></td>
        <td><%= vendor.phone %></td>
        <td><%= vendor.fname %></td>
        <td><%= vendor.lname %></td>
        <td><%= vendor.street %></td>
        <td><%= vendor.city %></td>
        <td><%= vendor.state.name %></td>
        <td><%= vendor.zipcode %></td>
        <td><%= link_to 'Show', vendor %></td>
        <td><%= link_to 'Edit', edit_vendor_path(vendor) %></td>
        <td><%= link_to 'Destroy', vendor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'New Vendor', new_vendor_path, method: :get %>

app/views/vendors/new.html.erb
<h1>New Vendor</h1>

<%= render 'form', vendor: @vendor %>

<%= link_to 'Back', vendors_path %>

app/views/vendors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vendor.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @vendor.phone %>
</p>

<p>
  <strong>Fname:</strong>
  <%= @vendor.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @vendor.lname %>
</p>

<p>
  <strong>Street:</strong>
  <%= @vendor.street %>
</p>

<p>
  <strong>City:</strong>
  <%= @vendor.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @vendor.state.name %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @vendor.zipcode %>
</p>

<%= link_to 'Edit', edit_vendor_path(@vendor) %> |
<%= link_to 'Back', vendors_path %>