config/routes.rb
Rails.application.routes.draw do
  get 'location/index'
  get 'expense_report', to: "expense_report#index"
  post 'expense_report', to: "expense_report#index"
  resources :order_items
  resources :items
  resources :order_vendors
  resources :vendors
  resources :states
  resources :orders
  resources :statuses
  get 'menu/index'
  get 'menu/dessert'
  get 'menu/beverages'
  get 'menu/sideitems'
  get 'menu/vermicelli'
  get 'menu/friedriceplate'
  get 'menu/steamedriceplate'
  get 'menu/eggnoodlesoup'
  get 'menu/chickennoodlesoup'
  get 'menu/special'
  get 'menu/beefnoodlesoups'
  get 'menu/appetizers'
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense_report.rb
class ExpenseReport

  def self.buy_by_product_in_range(starting,ending)
    Order.where("date_of_purchase >= '#{starting}' and date_of_purchase <= '#{ending}'")# .group(:product).count
  end

  def self.buy_in_range_arel(starting,ending)
    orders = Order.arel_table
    Order.where(orders[:date_of_purchase].between(starting..ending))# .group(:product).count
  end

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_items
  has_many :orders, through: :order_items

  validates_presence_of :name
  validates :price, numericality: {greater_than: 0}

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :status
  has_many :order_vendors, dependent: :destroy
  has_many :vendors, through: :order_vendors

  has_many :order_items, dependent: :destroy
  has_many :items, through: :order_items

  validates_presence_of :name

  after_save :calculate_total

  accepts_nested_attributes_for :order_vendors, :allow_destroy => true
  accepts_nested_attributes_for :order_items, :allow_destroy => true

  def calculate_total
    # sub_total = menu_items.map(&:price).sum * menu_orders.collect {|| .}
    sub_total = order_items.collect { |li| li.valid? ? (li.quantity * li.item.price ) : 0 }.sum
    tax = sub_total * 0.10
    update_columns(sub_total: sub_total, tax: tax)
  end

  def total_amount
    sub_total + tax
  end


  def self.sum_price
    Order.sum(:total_amount)
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

  validates :quantity, numericality: {greater_than: 0}

end

app/models/order_vendor.rb
class OrderVendor < ApplicationRecord
  belongs_to :vendor
  belongs_to :order
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  belongs_to :state
  has_many :order_vendors
  has_many :orders, through: :order_vendors

  validates_presence_of :name
  validates_presence_of :street
  validates_presence_of :zipcode
  validates_presence_of :city
  validates :fname, presence: true
  validates :lname, presence: true
  validates :phone, format: { with: /\d{3}-\d{3}-\d{4}/, message: "bad format" }



end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :price, :description)
    end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def appetizers
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/order_vendors_helper.rb
module OrderVendorsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table class="greenTable">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= number_to_currency(item.price) %></td>
        <td><%= item.description %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'New Item', new_item_path, method: :get %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@item.price) %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>